server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Evgen-88/ConfigStorage.git
          clone-on-start: true
  security:
    user:
      name: evgen
      password: evgen