server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Evgen-88/ConfigStorage.git
          clone-on-start: true
        encrypt:
          enabled: false
  security:
    user:
      name: evgen
      password: evgen
encrypt:
  key: 0ver5ecretpa55w0rd