server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: ${PROPERTY_PATH}
          clone-on-start: true
        encrypt:
          enabled: false
  security:
    user:
      name: ${USER_NAME}
      password: ${PASSWORD}
encrypt:
  key: ${SECRET}
